name             'php-cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures php-wrapper'
long_description 'Installs/Configures php-wrapper'
version          '0.1.0'

depends 'apt'
depends 'php'
